### ISSUE TITLE
Tailwind css

### ISSUE THREAD

**Issue by hakimj96** [Kamona-WD/kui-laravel-breeze#27]
Hi, im kinda new to tailwind, when i install the kui-laravel-breeze, and tried to use some class (https://tailwindcss.com/docs/border-radius#pill-buttons - by referring to tailwind docs) to check whether its working or not. So far its not going well for me. Can you advise on what step did i miss? Or do i need to import other tailwind configuration outside your readme? Thank you

Below is the code im trying
<img width="686" alt="Screenshot 2023-05-17 at 4 41 35 PM" src="https://github.com/Kamona-WD/kui-laravel-breeze/assets/27670318/267211f3-fe61-4d9c-8ed3-1325ce913920">

This is the output
<img width="674" alt="Screenshot 2023-05-17 at 4 42 07 PM" src="https://github.com/Kamona-WD/kui-laravel-breeze/assets/27670318/256e889d-791b-4a2b-b047-1304ca604b8c">

**Comment by Kamona-WD** [comment]
Use button component `<x-button pill>Save Changes</x-button>`
